### ISSUE TITLE
OBD Hardware

### ISSUE THREAD

**Issue by njordan77** [EVNotify/EVNotiPi#29]
Sorry if i misuse the issues log but i do not see another way to ask questions regarding EVnotiPi.
From what i see in the files, the used OBD Hat is from DIAMEX, right?

Is this specific hardware or its rather generic and these would work as well (especially as i orderred Sparkfun already).
* https://www.sparkfun.com/products/9555 
* https://freematics.com/store/index.php?route=product/product&product_id=83

**Comment by noradtux** [comment]
The Sparkfun adapter probably needs a different init sequence, but generally it should be usable.

**Comment by njordan77** [comment]
Thanks - sorry i've no expertise in OBD2 communication. regarding init sequence - where could i find this out. Try if it works without changing and if not looking into the sparkfun documentation?
Should arrive in about 2 weeks, so looking forward to start playing with the hardware...

How does EVnotipi detect the batteryvoltage > 13,5V....is this extra hardware that triggers such voltage changes?

**Comment by Jarry377** [comment]
Yes. A wemos D1 Mini is used to measure the voltage. 
Drawings and a list of needed parts will be available soon.

**Comment by njordan77** [comment]
thanks for the feeback. wemos why? clearly right now i have no picture of how it all works together. but why not let the Pi make this taks directly, maybe I2C ADC? so how will PI receive information, via WLAN from Wemos?

REally would love to digg deeper but right now i could not find any place where this project is decribed a little with more details. Would love to support if needed. REgards

**Comment by Jarry377** [comment]
The Wemos measures the voltage, and power up the OBD Hat (With the Raspi) via a relay shield.
if the voltage drops below 12,8V it set a GPIO of the Raspi to 3,3V which initiates a shutdown of the raspi. 40seconds later, the relay shield will cut the power to the OBD Hat

**Comment by njordan77** [comment]
Thanks a lot - really grateful if i can get more details as i will soon build my system up (based on the Sparkfun UART shield).

So you directly take the A0 from WEMOS and put a voltage divider before...but why the WEMOS....its too complex for this simple task. ATTiny + MOSFET instead of a mechnical relais.....again, no challenging, just trying to understand the details.....so you do not bring Raspi to sleep but directly shutdown the system..... 

So after a certain time of below 12,8V.....you first shutdown the Raspi + put the OBD from the car....
right? So the WEMOS will stay awake all the time to bring OBD+Raspi online again if higher than 13V?

I guess you take the power supply for the Raspi directly from the OBD 12V.
What device (step down?) are you using to generate the 5V for the Raspi....

Sorry for these many questions, what i really would love to do instead of the Raspi (and its perfromance would be able to handle)....exchange the Raspi against ESP32 or even ESP8266/Wemos,....

**Comment by Jarry377** [comment]
one reason was, that other people can build the box by themself without planning a PCB and ordering all these parts and solder them together, flash the ATTiny. Yes the Wemos has much more power than needed. Feel free to change it.
the Wemos is cheap as dirt and everyone can push the sketch on it. dosn't make sense to save 2 or 3 Bucks but create much more complexity in building it up.

**Comment by njordan77** [comment]
OK thanks. again - i do not want to challange the project - simply learn from your intentions+working platform. is there any overall scheme/electric plan available - even if only drafted. I'm highly interested to see how you did build it up....me personally i have no experience with OBD +CAN bus, My priority is to keep the 12V battery safe.

**Comment by Jarry377** [comment]
the drawing is wip :) gimme one or two days

**Comment by njordan77** [comment]
Thanks a lot for your effort. Looking forward to better understand the current solution!

One question - while I wait for my Sparkfun UART adapter. Is the current solution also able to handle bluetooth dongles (KONNWEI obding). I would like to try it the following way. Microcontroller powers/unpowers the dongle based on battery voltage.....+ starts/shutdowns the Raspberry. So only missing is if a bluetooth paired OBD dongle would find its way inside of  EVnotipi. Cheers and thanks for your thoughts on that. Norbert

**Comment by Jarry377** [comment]
This has to be answered by someone else. I am too stupid for Software stuff :)

**Comment by njordan77** [comment]
sorry, can you link me. is there a forum where all the discussion goes on about EVnotipi?

**Comment by Jarry377** [comment]
noradtux is already in this thread

**Comment by noradtux** [comment]
There is support for ELM327-based dongles. But it is untested. In general these BT-dongles look just like another TTY to the software.

**Comment by noradtux** [comment]
> OK thanks. again - i do not want to challange the project - simply learn from your intentions+working platform. is there any overall scheme/electric plan available - even if only drafted. I'm highly interested to see how you did build it up....me personally i have no experience with OBD +CAN bus, My priority is to keep the 12V battery safe.

You might take a look at https://github.com/noradtux/EVNotiPi-HW, that's what I use. I am currently doing a redesign to remove the need to get the ON-signal from the fuse box, just like with the Wemos.

**Comment by noradtux** [comment]
Also https://github.com/noradtux/Android-GPSd-Client to get GPS-coordinates into that thing.

**Comment by njordan77** [comment]
Thanks just have seen the filled parts in the main page. right now reading its content. *thanks*

**Comment by njordan77** [comment]
First of all, sorry if we should switch to some other platform to continue the conversation. Just let me know!

Really grateful that you share all your effort here in the web, highly appreciated!!!
2 questions....
* I'm not getting how you extract the voltage by putting a high value R in series to the analog pin of the WEMOS. normally i use voltage divider. from my electrical knowledge a ADC would have high input resistor, so no current....and the full 12,xxV would arrive at A0..which is way too high (0...1V normally).

* How did you power the Raspi, did you directly enter with 5V at the PinHeader or you did put a MircoUSB cable? or via OBD Hat?

Thanks a lot Norbert

**Comment by Jarry377** [comment]
the Wemos has already an internal divider with 220k and 100k. The ADC of the ESP can work with 1V. With the external 1,2M in series, the input can go up to ~15V
The Raspi is powered by the OBD-Hat.

If you want, you can join the Slack workspace evnotify.slack.com where you can discuss with the developer (and me :) ) directly

**Comment by njordan77** [comment]
Hi, just tried Slack (did not know it) - but can I add a user and not create my own workspace? sorry.
-@220k/100k...i see, that seems to be the reason that some ESP8266 boards handle 3,3V@A0 and others only 1V.
I right now orderred on top the Diamex OBD hat as Bluetooth is a nightmare (interferes heavily with WLAN@RPI...many discussion to be found in the internet) and the Sparkfun takes some time to ship....kind of impatience :-)

As this is complex code, is there any kind of documentation/notes to see where i need to start from, which scripts to autostart at boot.....+ how you handle the Shutdown PIN@Piheader ? Thanks

**Comment by Jarry377** [comment]
if you give me your mail address, i can send you an invite to the slack workspace if you want

**Comment by njordan77** [comment]
please. norbert.jordan AFFE gmail.com

**Comment by GPlay97** [comment]
Since software was totally rewritten and made easier, it should be more clear now.

If you still have issues or questions, feel free to open a new issue :)
