### ISSUE TITLE
Ungereimtheiten die nicht zusammenpassen

### ISSUE THREAD

**Issue by StefanKi** [EVNotify/EVNotiPi#43]
Ich habe heute wieder mal ein wenig herumgebastelt und bin auf folgende Ungereimtheiten gestoßen die nicht zusammenpassen. Bei Gelegenheit vielleicht mal fixen, ist aber nix besonderes dabei.
Übrigends habe ich statt dem Wemos einen atmega88 Mikrocontroller verwendet und das Timing nachgebaut. Bei Interesse melden, ich gebe den Source gerne weiter.

1. shutdown pin timing
Im Wemossketchbeispiel im Readme wird der shutdownpin für 3s geschaltet, aber im script shutdown.py wird mindestens 10s (MAX_FAIL) gefordert.
Einfach mal die Zeiten aneinander anpassen...

2. runs/runs.sh Scriptname falsch
In Zeile 10 von runs/runs.sh wird das Script evnotify.py gestartet.
evnotify.py gibts aber nicht, sondern das Script heißt dort evnotipi.py
Am besten den Dateinamen in Zeile 10 im Script einfach anpassen...

3. Ordnername EVNotiPi vs evnotipi
Wenn man laut dem Readme den Befehl "sudo git clone --recurse-submodules https://github.com/EVNotify/EVNotiPi" aufruft, dann ist der Ordnername EVNotiPi. Auch im Readme wird immer EVNotiPi geschrieben. In den scripts ist aber nicht EVNotiPi, sondern evnotipi drinnen. Da im Linux die Groß/Kleinschreibung relevant ist, funktionierts nicht.
Betroffen davon ist unter anderem die Readme, das Beispiel für die crontab im Readme und das runs/runs.sh Script.
Entweder den Ordner nach dem clonen umbennen lassen im Readme, oder die Ordnernamen in den Scripten umschreiben.

**Comment by GPlay97** [comment]
Die benannten Probleme sollten mittlerweile behoben worden sein durch einige Code-Änderungen.
Falls dem doch nicht sein sollte, bitte neues Issue erstellen.
